"""
Client Constants

"""
from enum import Enum


SCREEN_W = 80
SCREEN_H = 70

MAP_VIEWPORT_W = SCREEN_W
MAP_VIEWPORT_H = 50

STATS_CONSOLE_W = 20
STATS_CONSOLE_H = SCREEN_H - MAP_VIEWPORT_H - 1
STATS_CONSOLE_X = 0
STATS_CONSOLE_Y = SCREEN_H - STATS_CONSOLE_H

LOG_CONSOLE_W = 60
LOG_CONSOLE_H = SCREEN_H - MAP_VIEWPORT_H - 1
LOG_CONSOLE_X = SCREEN_W - LOG_CONSOLE_W
LOG_CONSOLE_Y = SCREEN_H - LOG_CONSOLE_H

ASSETS_PATH = 'client_tcod/assets'

MAP_DEBUG = False
MAP_DEBUG_DELAY = 20.0

SHOW_UNEXPLORED_CELLS = False
IGNORE_FOV = False

SHOW_PATH_INFO = False
SHOW_SPAWN_ZONES = False


class TileType(Enum):
    FLOOR = '.'
    WALL = '#'
